---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    groups:
      maven-plugin-dependencies:
        patterns:
          - "org.apache.maven.plugins*"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
